version: '3'

services: 

  mysqldb:
    container_name: sql_userdb
    image: mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "user"
    volumes: 
      - ./data/pg:/var/lib/mysql

  user: 
    container_name: user_microservice
    build: ./Users
    restart: always
    ports: 
      - 8080:8080
    depends_on: 
      - mysqldb
     
  feeddb:
    container_name: feed_db
    image: 
      mongo
    volumes: 
      - ./data/feed/:/data/db

  feed:
    container_name: feed_microservice
    build: ./feed
    ports: 
      - 8070:8070
    depends_on: 
      - feeddb

  authdb:
    container_name: auth_db
    image: 
      mongo
    volumes: 
      - ./data/auth/:/data/db
  
  auth:
    container_name: authentication_service
    build: ./Auth
    ports: 
      - 8082:8082
    depends_on: 
      - authdb
  
  chatdb:
    container_name: chatdb
    image:
      mongo
    volumes: 
      - ./data/chatDB/:/data/db
  
  roomdb:
    container_name: roomdb
    image:
      mongo
    volumes: 
      - ./data/roomDB/:/data/db
  
  chat:
    container_name: chat
    build: ./Chat
    ports:
      - 8085:8085
    depends_on:
      - chatdb
      - roomdb

