version: '3'

services: 
  mysql:
    image: mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'user'
      MYSQL_USER: 'root'

  user: 
    build: .
    ports: 
      - 8080:8080
    depends_on: 
      - mysql
     
